import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
 /** @jsxImportSource @emotion/react */
import { jsx, css } from '@emotion/react'
import styled from '@emotion/styled'



export default function Home()
{

  const base1 = css`color: hotpink;`

  const danger = css`
  color: red;
`

  const base2 = css`
  background-color: darkgreen;
  color: turquoise;
`

const Button = styled.button(
{
  color: 'darkorchid'
},
props => (
{
  fontSize: props.fontSize
}))

  return (
    <div className={styles.container}>
      <Head>
        <title>Emotions Compositions App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
          css={css`
          ${base1};
          background-color: #eee;`}>This is hotpink</div>


      <div>
        <style>
        {`
          .danger
          {
            color: red;
          }
          .base
          {
            background-color: lightgray;
            color: turquoise;
          }`}
        </style>
        <p className="base danger">What color will this be?</p>
      </div>

      <div>
        <div css={base2}>This will be turquoise</div>
          <div css={[danger, base2]}>
            This will be also be turquoise since the base styles
            overwrite the danger styles.
          </div>
        <div css={[base2, danger]}>This will be red</div>
      </div>

      <br/>
      <div
          css=
          {{
              color: 'darkorchid',
              backgroundColor: 'lightgray'
          }}>This is darkorchid</div>

      <br/>
      <Button fontSize={16}>This is a darkorchid button.</Button>

      <br/>
      <div
          css=
          {{
            padding: 8,
            zIndex: 200
          }}>This has 8px of padding and a z-index of 200</div>

    </div>
  )
}
