import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styled from '@emotion/styled'
import logo from '../images/pokemon_logo.png'
import Link from 'next/link'



/** @param {import('next').InferGetStaticPropsType<typeof getStaticProps> } props */
export default function Home(props)
{
    const [pokemon,putPokemon] = useState([])
    const [query,setQuery]=useState('');

    /*const searchPokemon = (e) =>{
        e.preventDefault();
        console.log('Searched for', query);
        fetch(`https://pokeapi.co/api/v2/pokemon/${query}`).then((resp)=>resp.json()).then(data=>{
            putPokemon(data);
            console.log(data);
        });
    };*/

    const PokemonDetails = styled.section `
        background-color:white;
        padding-bottom: 5px;
        height: auto;
        width: 250px;
        margin-left: 32px;
        margin-top: 8px;
        visibility: hidden;`

    const PokemonName = styled.button`
        padding: 10px;
        background-color: black;
        font-size: 24px;
        border-radius: 50px;
        color: black;
        font-weight: bold;
        margin-left: 32px;
        margin-top: 16px;
        position: fixed;
        bottom: 0px;
        right:550px ;
        margin-bottom: 70px;
        &:hover
        {
            color: red;
        }`

    const PokemonType = styled.button`
        padding: 10px;
        background-color: black;
        font-size: 24px;
        border-radius: 50px;
        color: black;
        font-weight: bold;
        margin-left: 32px;
        margin-top: 16px;
        position: fixed;
        bottom: 0px;
        right:650px ;
        margin-bottom: 10px;
        &:hover
        {
            color: yellow;
        }`


    const Nested = styled('span')`
        font-size: 24px;
        color: yellowgreen;
        margin-left: 32px;
        font-weight: bold;
        position: fixed;
        bottom: 0px;
        left: 0px;
        margin-bottom: 80px;
        & > b
        {
            color: hotpink;
            font-size: 24px;
        }`

    const Normal = styled('span')`
        font-size: 24px;
        color: orangered;
        margin-left: 32px;
        font-weight: bold;
        position: fixed;
        bottom: 0px;
        left: 0px;
        margin-bottom: 20px;`

    return (
        <div>
            <Head>
                <title>Pokedex API</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"/>
                </Head>
            <main>
                <div id="search-box" classNameName="bg-primary w-100 p-2" style={{backgroundColor:"blue", padding:15,
                                                display: "flex", alignItems: "center"}}>
			        <div classNameName="row m-0" style={{justifyContent:"initial", paddingInlineStart:100}}>
                        <Image src={logo} alt="Pokemon" height="60" width="160" />
                    </div>
                    <div classNameName='col-md-9' style={{textAlign:"right", paddingInlineStart:790}}>
					    <form classNameName="mb-0  d-flex justify-content-center align-items-center h-100 w-100">
						    <div>
							    <input id="search_name" style={{padding: 10, borderTopLeftRadius: 30
                                                                        , borderBottomLeftRadius: 30}}
                                    type="text"
                                    value={query}
                                    onChange={(e)=>{setQuery(e.currentTarget.value);}}
                                    placeholder="Enter Pokemon Name"/>

                                <input id="submit_button" style={{padding: 10, borderTopRightRadius: 30
                                                                        , borderBottomRightRadius: 30}}
                                    onClick={(e)=>{
                                    e.preventDefault();
                                    console.log("searched for "+query)
                                    fetch(`https://pokeapi.co/api/v2/pokemon/${query}`)
                                    .then((resp)=>resp.json())
                                    .then(data=>
                                    {
                                        putPokemon(data);
                                        console.log(data);
                                    });}}
                                    type="submit" value="Search"
                                    classNameName="btn btn-light p-2" />
						    </div>
					    </form>
				    </div>
                </div>

                {pokemon?.name &&
                    <PokemonDetails style={{visibility: "visible"}}>
                        {pokemon?.sprites && (
                            <img src={pokemon.sprites.front_default} align="left" height="100" width="110"/>)}
                        <br/>
                        <h1>{pokemon?.name.toUpperCase()}</h1>
                        <br/>

                        {pokemon?.types?.length > 0 && (
                        <ul>
                            <b>Type:</b>
                            {
                                pokemon.types.map((t) =>
                                {
                                    // eslint-disable-next-line react/jsx-key
                                    return <b> {t.type.name.toUpperCase()}</b>
                                })
                            }
                        </ul>
                        )}

                        
                        {pokemon?.types?.length > 0 && (
                        <ul>
                            <b>Abilities: </b>
                            {

                                pokemon.abilities.map((t) =>
                                {
                                    // eslint-disable-next-line react/jsx-key
                                    return <b>{t.ability.name.toUpperCase()}, </b>
                                })
                            }
                        </ul>
                        )}
                    </PokemonDetails>
                }

                <Nested>New to Pokemon, <b>Click the button to see some of the Pokemons</b></Nested>
                <Link href="/pokemonnames">
                    <a>
                        <PokemonName>Pokemon Names</PokemonName>
                    </a>
                </Link>

                <Normal>Click the button to see various kinds/types of Pokemon</Normal>
                <Link href="/types/pokemontypes">
                    <a>
                        <PokemonType>Pokemon Types</PokemonType>
                    </a>
                </Link>
            </main>
        </div>
    )
}
