import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styled from '@emotion/styled'
import logo from '../images/pokemon_logo.png'
import Link from 'next/link'




export default function Home(props)
{
    const [pokemon,putPokemon] = useState([])
    const [query,setQuery]=useState('');

    /*const searchPokemon = (e) =>{
        e.preventDefault();
        console.log('Searched for', query);
        fetch(`https://pokeapi.co/api/v2/pokemon/${query}`).then((resp)=>resp.json()).then(data=>{
            putPokemon(data);
            console.log(data);
        });
    };*/


    const PokemonName = styled.button`
        padding: 10px;
        background-color: black;
        font-size: 24px;
        border-radius: 50px;
        color: black;
        font-weight: bold;
        margin-left: 32px;
        margin-top: 16px;
        position: fixed;
        bottom: 0px;
        right:550px ;
        margin-bottom: 70px;
        &:hover
        {
            color: red;
        }`

    const PokemonType = styled.button`
        padding: 10px;
        background-color: black;
        font-size: 24px;
        border-radius: 50px;
        color: black;
        font-weight: bold;
        margin-left: 32px;
        margin-top: 16px;
        position: fixed;
        bottom: 0px;
        right:650px ;
        margin-bottom: 10px;
        &:hover
        {
            color: yellow;
        }`

    return (
        <div>
            <Head>
                <title>Pokedex API</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"/>
            </Head>
            
            <main>

            <nav className="flex-wrap py-3 bg-blue-600 shadow-lg ">
		        <div className="max-w-6xl px-4 mx-auto">
			        <div className="flex justify-between">
				        <div className="flex space-x-7">
					        <div>
					            <a href="#" className="flex items-center ">
						            <Image src={logo} alt="Logo" className="" width="180" height="70"/>
					            </a>
				            </div>
				        </div>
                        <div className="items-center hidden md:flex ">
                            <input id="search_name" className="p-2 " style={{borderTopLeftRadius: 30
                                                                        , borderBottomLeftRadius: 30}}
                                    type="text"
                                    value={query}
                                    onChange={(e)=>{setQuery(e.currentTarget.value);}}
                                    placeholder="Enter Pokemon Name"/>

                            <input id="submit_button" style={{borderTopRightRadius: 30
                                                                        , borderBottomRightRadius: 30}}
                                    onClick={(e)=>{
                                    e.preventDefault();
                                    console.log("searched for "+query)
                                    fetch(`https://pokeapi.co/api/v2/pokemon/${query}`)
                                    .then((resp)=>resp.json())
                                    .then(data=>
                                    {
                                        putPokemon(data);
                                        console.log(data);
                                    });}}
                                    type="submit" value="Search"
                                    className="p-2 btn btn-light" />

                            <div className="items-center hidden ml-24 space-x-24 md:flex">
							    <Link href="/pokemonnames" className="px-2 py-4 font-semibold text-green-500 border-b-4 border-green-500 ">Names</Link>
							    <Link href="/types/pokemontypes" className="px-2 py-4 font-semibold text-gray-500 transition duration-300 hover:text-green-500">Types</Link>
    						</div>
					    </div>
                        {/* 
                        <div className="flex items-center md:hidden">
						    <button className="outline-none mobile-menu-button">
						        <svg className="w-6 h-6 text-gray-500 hover:text-green-500"
							        x-show="!showMenu"
							        fill="none"
							        strokeLinecap="round"
							        strokeLinejoin="round"
							        strokeWidth="2"
							        viewBox="0 0 24 24"
							        stroke="currentColor"><path d="M4 6h16M4 12h16M4 18h16"></path></svg>
					        </button>
					    </div>*/}
			        </div>

                    <label htmlFor="menu_toggle" className="flex items-center cursor-pointer md:hidden">
                        <svg className="text-gray-900 fill-current" xmlns="http://www.w3.org/2000/svg" width="30" height="30">
                            <title>menu</title>
                            <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
                        </svg>
                    </label>
                    <input type="checkbox" className="hidden" id="menu-toggle"></input>


		        </div>


                {/*<div class="hidden mobile-menu">
				<ul class="">
					<li classN="active"><a href="index.html" class="block text-sm px-2 py-4 text-white bg-green-500 font-semibold">Home</a></li>
					<li><a href="#services" class="block text-sm px-2 py-4 hover:bg-green-500 transition duration-300">Services</a></li>
					<li><a href="#about" class="block text-sm px-2 py-4 hover:bg-green-500 transition duration-300">About</a></li>
					<li><a href="#contact" class="block text-sm px-2 py-4 hover:bg-green-500 transition duration-300">Contact Us</a></li>
				</ul>
			</div> 
			<script>
				const btn = document.querySelector("button.mobile-menu-button");
				const menu = document.querySelector(".mobile-menu");

				btn.addEventListener("click", () => {
					menu.classList.toggle("hidden");
				});
			</script>*/}
	        </nav>

            {pokemon?.name &&
                <div className="bg-white pb-1.5 h-auto w-60 ml-8 mt-2" >
                {pokemon?.sprites && (
                    <img src={pokemon.sprites.front_default} align="left" height="100" width="110"/>)}
                        <br/>
                        <h1>{pokemon?.name.toUpperCase()}</h1>
                        <br/>

                        {pokemon?.types?.length > 0 && (
                        <ul>
                            <b>Type:</b>
                            {
                                pokemon.types.map((t) =>
                                {
                                    // eslint-disable-next-line react/jsx-key
                                    return <b> {t.type.name.toUpperCase()}</b>
                                })
                            }
                        </ul>
                        )}

                        
                        {pokemon?.types?.length > 0 && (
                        <ul>
                            <b>Abilities: </b>
                            {

                                pokemon.abilities.map((t) =>
                                {
                                    // eslint-disable-next-line react/jsx-key
                                    return <b>{t.ability.name.toUpperCase()}, </b>
                                })
                            }
                        </ul>
                        )}
                    </div>
                }
            </main>
        </div>
    )
}
