import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled from '@emotion/styled'

export default function Home()
{

  //Styling a text
  const Basic = ({ className }) => (
    <div className={className}>WELCOME</div>
  )

  const Button1 = styled.button`
  color: grey;`

  // Changing based on Props
  const Button2 = styled.button`
  color: ${props =>
    props.primary ? 'black' : 'royalblue'};`

  const Container = styled.div(props => (
  {
    display: 'flex',
    flexDirection: props.column && 'column'
  }))

  const Fancy = styled(Basic)`
    color: hotpink;`

  return (
    <div className={styles.container}>
      <Head>
        <title>Emotion App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Fancy/>
      <br/>

      <Button1>NORMAL BUTTON</Button1>
      <br/>

      <Container column>
        <Button2>REGULAR BUTTON PROP</Button2>
        <br/>
        <Button2 primary>PRIMARY BUTTON PROP</Button2>
      </Container>
      <br/>
      

    </div>
  )

}
