import lalettan from '../public/mohanlal.jpg'
import rogphone from '../public/rog.jpg'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import logo from '../public/chatlogo.jpg'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tail Wind App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <div className="max-w-sm px-8 py-8 mx-auto bg-pink-200 shadow-md mt-96 sm:py-4 sm:flex sm:space-y-0 sm:space-x-6">
          <Image className="block h-24 mx-auto rounded-full sm:mx-0 sm:flex-shrink-0" src={ lalettan } alt="Mohanlal"/>
          <div className="space-y-2 text-center sm:text-center">
            <div className="space-y-0.5">
              <p className="text-lg font-semibold text-black">MOHANLAL</p>
              <p className="font-medium text-gray-500">Actor</p>
            </div>
            <button className="px-4 py-1 text-sm font-semibold text-purple-600 border border-purple-200 rounded-full hover:text-white hover:bg-purple-600 hover:border-transparent focus:outline-none focus:ring-2 focus:ring-purple-600 focus:ring-offset-2">Message</button>
          </div>
        </div>
        <br/>


        <div className="flex items-center max-w-sm p-6 mx-auto mb-12 space-x-4 bg-pink-100 shadow-md rounded-xl">
        <div className="flex-shrink-0">
            <Image className="w-12 h-12" src={logo} alt="Vercel Logo" height = "50px" width = "50px" />
          </div>
          <div>
            <div className="text-xl font-medium text-black">ChitChat</div>
            <p className="text-gray-500">You have a new message!</p>
          </div>
        </div>
        <br/>


    


        <div className="max-w-md mx-auto mb-8 overflow-hidden bg-pink-300 shadow-md rounded-xl md:max-w-max">
          <div className="md:flex">
            <div className="md:flex-shrink-0">
              <Image className="h-2 bg-pink-300 md:h-full md:w-48" src={rogphone} alt="Mob Responsive Content"/>
            </div>
            <div className="p-8">
                <a href="https://rog.asus.com/phones/rog-phone-5s-pro-model/" className="block mt-1 text-lg font-medium leading-tight text-black hover:underline">ASUS ROG PHONE 5s PRO</a>
                <p className="mt-2 text-gray-500">Snapdragon 888+, 144Hz sAmoled Display, 18 GB LPDDR5 RAM, 512 GB UFS 3.1 Storage, 6000 mAh Battery, Airtriggers 5, ROG Vision, Dual Stereo Speakers, 64MP Triple Camera</p>
              </div>
            </div>
        </div>

      </main>
    </div>
  )
}
